service: nft-metadata-generator

frameworkVersion: '3'

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs18.x
  stage: dev
  region: eu-central-1

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env

functions:
  generate:
    handler: generator.handler
    timeout: 30
    events:
      - http:
          path: /generate-image-url
          method: get
      - http:
          path: /pin-image-to-pinata
          method: get
      - http:
          path: /generate-metadata-json
          method: get
      - http:
          path: /pin-metadata-to-pinata
          method: post
